apiVersion: batch/v1
kind: Job
metadata:
  name: cntxtapitodo-job
spec:
  template:
    spec:
      containers:
      - name: cntxtapitodo-job
        image: yash5090/cntxtapitodo:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
