apiVersion: apps/v1
kind: Deployment
metadata:
  name: cntxtapitodo-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: cntxtapitodo
  template:
    metadata:
      labels:
        app: cntxtapitodo
    spec:
      containers:
        - name: cntxtapitodo
          image: yash5090/cntxtapitodo:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
